apiVersion: console.openshift.io/v1
kind: ConsolePlugin
metadata:
  name: portail-console-plugin
spec:
  backend:
    service:
      basePath: /
      name: portail-console-plugin
      namespace: portail-operator-system
      port: 9443
    type: Service
  displayName: Portail Network Topology
