import { useMemo } from 'react';
import {
  CONTROLLER_NAME,
  NETWORK_ADDRESS_TYPE,
  EXTERNAL_NODE_ID,
  CLUSTER_DEFAULT_NODE_ID,
} from '../constants';
import {
  GraphModel,
  TopologyNode,
  TopologyEdge,
  GatewayResource,
  GatewayClassResource,
  NetworkAttachmentDefinitionResource,
  UserDefinedNetworkResource,
  HTTPRouteResource,
  ListenerInfo,
  GatewayCondition,
  RouteNodeData,
} from '../types';

function nadNodeId(nad: NetworkAttachmentDefinitionResource): string {
  return `nad/${nad.metadata?.namespace}/${nad.metadata?.name}`;
}

function udnNodeId(udn: UserDefinedNetworkResource): string {
  return `udn/${udn.metadata?.namespace}/${udn.metadata?.name}`;
}

function extractUdnCidr(udn: UserDefinedNetworkResource): string | undefined {
  const l3Subnets = udn.spec?.layer3?.subnets;
  if (l3Subnets?.length) {
    return l3Subnets.map((s) => s.cidr).join(', ');
  }
  const l2Subnets = udn.spec?.layer2?.subnets;
  if (l2Subnets?.length) {
    return l2Subnets.map((s) => s.cidr).join(', ');
  }
  return undefined;
}

function extractListeners(gw: GatewayResource): ListenerInfo[] {
  return (gw.spec.listeners ?? []).map((l) => ({
    name: l.name,
    protocol: l.protocol,
    port: l.port,
    hostname: l.hostname,
  }));
}

function extractConditions(gw: GatewayResource): GatewayCondition[] {
  return (gw.status?.conditions ?? []).map((c) => ({
    type: c.type,
    status: c.status,
    reason: c.reason,
    message: c.message,
    lastTransitionTime: c.lastTransitionTime,
  }));
}

function extractAddresses(gw: GatewayResource): string[] {
  return (gw.status?.addresses ?? []).map((a) => a.value);
}

function getNetworkNames(gw: GatewayResource): string[] {
  return (gw.spec.addresses ?? [])
    .filter((a) => a.type === NETWORK_ADDRESS_TYPE)
    .map((a) => a.value);
}

function findNetworkNodeId(
  networkName: string,
  nadMap: Map<string, string>,
  udnMap: Map<string, string>,
): string | undefined {
  return udnMap.get(networkName) ?? nadMap.get(networkName);
}

export const useTopologyGraph = (
  gateways: GatewayResource[],
  gatewayClasses: GatewayClassResource[],
  nads: NetworkAttachmentDefinitionResource[],
  udns: UserDefinedNetworkResource[],
  httpRoutes: HTTPRouteResource[],
): GraphModel => {
  return useMemo(() => {
    // Find GatewayClasses managed by Portail
    const managedClassNames = new Set(
      gatewayClasses
        .filter((gc) => gc.spec.controllerName === CONTROLLER_NAME)
        .map((gc) => gc.metadata?.name)
        .filter(Boolean),
    );

    // Build nodes
    const nodes: TopologyNode[] = [];

    // Synthetic External node (left zone)
    nodes.push({
      id: EXTERNAL_NODE_ID,
      type: 'external',
      label: 'External',
      zone: 'external',
      data: { networkType: 'cluster-default' },
    });

    // Synthetic cluster-default node (right zone)
    nodes.push({
      id: CLUSTER_DEFAULT_NODE_ID,
      type: 'network',
      label: 'cluster-default',
      zone: 'cluster',
      data: { networkType: 'cluster-default' },
    });

    // Collect UDN names to skip NADs that are auto-generated by OVN-K
    const udnKeys = new Set(
      udns.map((udn) => `${udn.metadata?.namespace}/${udn.metadata?.name}`),
    );

    // NAD nodes — skip those owned by a UDN (label: k8s.ovn.org/user-defined-network)
    const nadMap = new Map<string, string>();
    for (const nad of nads) {
      const labels = nad.metadata?.labels as Record<string, string> | undefined;
      const isUdnGenerated = labels?.['k8s.ovn.org/user-defined-network'] !== undefined;
      const key = `${nad.metadata?.namespace}/${nad.metadata?.name}`;
      if (isUdnGenerated && udnKeys.has(key)) {
        continue; // UDN node will represent this network with richer data
      }
      const id = nadNodeId(nad);
      const name = nad.metadata?.name ?? 'unknown';
      nadMap.set(name, id);
      nodes.push({
        id,
        type: 'network',
        label: name,
        zone: 'cluster',
        data: {
          networkType: 'nad',
          namespace: nad.metadata?.namespace,
          resource: nad,
        },
      });
    }

    // UDN nodes
    const udnMap = new Map<string, string>();
    for (const udn of udns) {
      const id = udnNodeId(udn);
      const name = udn.metadata?.name ?? 'unknown';
      udnMap.set(name, id);
      nodes.push({
        id,
        type: 'network',
        label: name,
        zone: 'cluster',
        data: {
          networkType: 'udn',
          namespace: udn.metadata?.namespace,
          cidr: extractUdnCidr(udn),
          resource: udn,
        },
      });
    }

    // Build edges from managed Gateways
    const edges: TopologyEdge[] = [];
    const managedGateways = gateways.filter(
      (gw) => managedClassNames.has(gw.spec.gatewayClassName),
    );

    // Map gateway name to edge IDs for route attachment
    const gatewayEdgeMap = new Map<string, string>(); // "ns/name" -> edgeId

    for (const gw of managedGateways) {
      const gwName = gw.metadata?.name ?? 'unknown';
      const gwNamespace = gw.metadata?.namespace ?? 'default';
      const networkNames = getNetworkNames(gw);
      const listeners = extractListeners(gw);
      const conditions = extractConditions(gw);
      const addresses = extractAddresses(gw);

      const edgeBase = {
        type: 'gateway' as const,
        label: gwName,
        data: {
          gatewayName: gwName,
          gatewayNamespace: gwNamespace,
          gatewayClassName: gw.spec.gatewayClassName,
          listeners,
          conditions,
          addresses,
          resource: gw,
        },
      };

      if (networkNames.length === 0) {
        // LoadBalancer mode: External → cluster-default
        const edgeId = `gw/${gwNamespace}/${gwName}`;
        gatewayEdgeMap.set(`${gwNamespace}/${gwName}`, edgeId);
        edges.push({
          ...edgeBase,
          id: edgeId,
          source: EXTERNAL_NODE_ID,
          target: CLUSTER_DEFAULT_NODE_ID,
          data: { ...edgeBase.data, mode: 'loadbalancer' },
        });
      } else if (networkNames.length === 1) {
        // Single network: cluster-default → that network
        const edgeId = `gw/${gwNamespace}/${gwName}`;
        gatewayEdgeMap.set(`${gwNamespace}/${gwName}`, edgeId);
        const targetId = findNetworkNodeId(networkNames[0], nadMap, udnMap) ?? CLUSTER_DEFAULT_NODE_ID;
        edges.push({
          ...edgeBase,
          id: edgeId,
          source: CLUSTER_DEFAULT_NODE_ID,
          target: targetId,
          data: { ...edgeBase.data, mode: 'multi-network' },
        });
      } else {
        // Multiple networks: create edges between consecutive pairs
        for (let i = 0; i < networkNames.length - 1; i++) {
          const edgeId = `gw/${gwNamespace}/${gwName}/${i}`;
          if (i === 0) {
            gatewayEdgeMap.set(`${gwNamespace}/${gwName}`, edgeId);
          }
          const sourceId = findNetworkNodeId(networkNames[i], nadMap, udnMap) ?? CLUSTER_DEFAULT_NODE_ID;
          const targetId = findNetworkNodeId(networkNames[i + 1], nadMap, udnMap) ?? CLUSTER_DEFAULT_NODE_ID;
          edges.push({
            ...edgeBase,
            id: edgeId,
            source: sourceId,
            target: targetId,
            data: { ...edgeBase.data, mode: 'multi-network' },
          });
        }
      }
    }

    // Build HTTPRoute nodes and edges
    for (const route of httpRoutes) {
      const routeName = route.metadata?.name ?? 'unknown';
      const routeNamespace = route.metadata?.namespace ?? 'default';
      const parentRefs = route.spec.parentRefs ?? [];

      for (const parentRef of parentRefs) {
        // Only process Gateway parentRefs (default kind is Gateway)
        const refKind = parentRef.kind ?? 'Gateway';
        if (refKind !== 'Gateway') continue;

        const refNamespace = parentRef.namespace ?? routeNamespace;
        const gwKey = `${refNamespace}/${parentRef.name}`;
        const gatewayEdgeId = gatewayEdgeMap.get(gwKey);

        if (!gatewayEdgeId) continue; // Not a managed gateway

        // Find the target node of the gateway edge to place route near it
        const gwEdge = edges.find((e) => e.id === gatewayEdgeId);
        if (!gwEdge) continue;

        const routeNodeId = `route/${routeNamespace}/${routeName}`;
        const backendCount = (route.spec.rules ?? []).reduce(
          (acc, r) => acc + (r.backendRefs?.length ?? 0), 0,
        );

        // Only add the route node once (avoid duplicates for multiple parentRefs)
        if (!nodes.find((n) => n.id === routeNodeId)) {
          const routeData: RouteNodeData = {
            routeType: 'http',
            hostnames: route.spec.hostnames ?? [],
            rulesCount: route.spec.rules?.length ?? 0,
            backendCount,
            parentGatewayEdgeId: gatewayEdgeId,
            namespace: routeNamespace,
            resource: route,
          };

          nodes.push({
            id: routeNodeId,
            type: 'route',
            label: routeName,
            zone: 'cluster',
            data: routeData,
          });
        }

        // Create edge from the gateway's target node to the route node
        edges.push({
          id: `route-edge/${routeNamespace}/${routeName}/${parentRef.name}`,
          type: 'route',
          source: gwEdge.target,
          target: routeNodeId,
          label: routeName,
          data: {
            routeName,
            routeNamespace,
            parentGateway: parentRef.name,
          },
        });
      }
    }

    return { nodes, edges };
  }, [gateways, gatewayClasses, nads, udns, httpRoutes]);
};
