apiVersion: v1
kind: Service
metadata:
  name: portail-console-plugin
  namespace: portail-operator-system
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: portail-console-plugin-cert
  labels:
    app.kubernetes.io/name: portail-console-plugin
    app.kubernetes.io/part-of: portail-operator
spec:
  selector:
    app.kubernetes.io/name: portail-console-plugin
  ports:
    - name: https
      port: 9443
      targetPort: 9443
      protocol: TCP
